#!/usr/bin/python

import os
import time
import sys


def printtime(h=0, m=0, s=0, icon="󰚭"):
    msg = f'{{"text":"{icon} '
    if h > 0:
        msg += f"{h:02d}:"
    if m > 0:
        msg += f"{m:02d}:"
    msg += f'{s:02d}"}}'
    print(msg)


fp = "/tmp/waybar-stopwatch"
if sys.argv[1] == "start":
    try:
        with open(fp, "r") as fh:
            start = float(fh.read())
        s = time.time() - start
        m = int(s // 60)
        s = int(s % 60)
        h = int(m // 60)
        m = int(m % 60)
        printtime(h, m, s, "󱦟")
    except Exception:
        printtime()

elif sys.argv[1] == "restart":
    if os.path.exists(fp):
        os.unlink(fp)
    else:
        with open(fp, "w") as fh:
            t = time.time()
            fh.write(f"{t:.2f}")

else:
    print('{"text": "ERROR", "tooltip":"error"}')
